### ISSUE TITLE
Request to Restore Previous Usage Method in ggview

### ISSUE THREAD

**Issue by Syutenjyo** [idmn/ggview#9]
Dear ggview package maintainer,
I have been a long-time user of the ggview package, which is an excellent extension to ggplot2. However, with the recent update, the usage method has significantly changed, rendering the old method completely ineffective.
Previously, the package could be used as follows:
```
p1 <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_wrap(vars(class), scales = "free")
ggview(p1, width = 8, height = 4.6)
```

But now, the new method is:
```
p1 <- ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  facet_wrap(vars(class), scales = "free") +
  canvas(width = 8, height = 4.6)

save_ggplot(p1, "my_plot.png")
```
I understand that updates are necessary for improvement and bug fixes, but the sudden change in usage has disrupted my workflow. I would greatly appreciate it if you could consider restoring the previous usage method. This would be extremely helpful for users like me who have become accustomed to the old way and have existing codebases that rely on it.
Thank you for your consideration and for your excellent work on this package.

**Comment by idmn** [comment]
Thanks for the kind words and for being a long-time user of ggview!

I understand the change in usage might be disruptive, but I believe the new interface—attaching dimensions directly to plots and applying them automatically—is a cleaner and more intuitive approach. Because of this, I don’t plan to reintroduce the old ggview() function to keep things minimalistic.

That said, the old function still exists in the package as an internal function. You can use it by adding this to your script:

```r
ggview <- ggview:::ggview
```

Hope this helps, and thanks again for your feedback!
